name: SonarCloud Analysis

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x'  # You can specify the .NET Core version you need

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Run SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ secrets.YOUR_SONARCLOUD_TOKEN }}
      run: dotnet sonarscanner begin /k:Glipchik_SecondMap /d:sonar.login="${{ env.SONAR_TOKEN }}" && dotnet build --configuration Release && dotnet sonarscanner end /d:sonar.login="${{ env.SONAR_TOKEN }}"

    - name: Test the project (Optional)
      run: dotnet test --no-restore --verbosity normal
